# Main entrypoint of the workflow.
# Please follow the best practices:
# https://snakemake.readthedocs.io/en/stable/snakefiles/best_practices.html,
# in particular regarding the standardized folder structure mentioned there.

import glob
import os


configfile: "config/config.yml"


input_dir = config["input_dir"]
output_dir = config["output_dir"]

# Collect sample names from test_data directory
SAMPLES = [os.path.basename(d) for d in glob.glob(f"{input_dir}/*") if os.path.isdir(d)]

# Get assemblers to run from config
ASSEMBLERS = [
    assembler for assembler, enabled in config.get("assemblers", {}).items() if enabled
]

KMER_STRATEGIES = [
    strategy for strategy, enabled in config.get("kmer_strategy", {}).items() if enabled
]

# include common rule (where functions are defined)
include: "rules/common.smk"


# Conditionally include kmergenie rule only if using kmergenie mode
if "kmergenie" in KMER_STRATEGIES:

    include: "rules/kmergenie.smk"


# Conditionally include seqkit rule only if using reads_length mode
if "reads_length" in KMER_STRATEGIES:

    include: "rules/seqkit.smk"


# if spades is in ASSEMBLERS include spades rules
if "spades" in ASSEMBLERS:

    include: "rules/spades.smk"


# if megahit is in ASSEMBLERS include megahit rules
if "megahit" in ASSEMBLERS:

    include: "rules/megahit.smk"


# if abyss is in ASSEMBLERS include abyss rules
if "abyss" in ASSEMBLERS:

    include: "rules/abyss.smk"


# if sparseassembler is in ASSEMBLERS include sparseassembler rules
if "sparseassembler" in ASSEMBLERS:

    include: "rules/decompress_reads.smk"
    include: "rules/sparseassembler.smk"


# if minia is in ASSEMBLERS include minia rules
if "minia" in ASSEMBLERS:

    include: "rules/minia.smk"


# if masurca is in ASSEMBLERS include masurca rules
if "masurca" in ASSEMBLERS:

    include: "rules/masurca.smk"


# include get_busco_db rule
include: "rules/get_busco_db.smk"
# include busco rule
include: "rules/busco.smk"
# include quast rule
include: "rules/quast.smk"
# include fastK rule
include: "rules/fastK.smk"
# include merquryFK rule
include: "rules/merquryFK.smk"
# include select_best_assembly rule
include: "rules/select_best_assembly.smk"
# include pypolca rule
include: "rules/pypolca.smk"
# include busco_2 rule (runs after pypolca)
include: "rules/busco_2.smk"
# include merquryFK_2 rule (runs after pypolca)
include: "rules/merquryFK_2.smk"
# include quast_2 rule (runs after pypolca)
include: "rules/quast_2.smk"
# include bwa_mem2 rule (runs after pypolca)
include: "rules/bwa_mem2.smk"
# include samtools rule (runs after pypolca)
include: "rules/samtools.smk"
# include coverage_viz rule
include: "rules/coverage_viz.smk"


# input files for rule all are defined in the common.smk file
rule all:
    input:
        get_all_inputs(),
