# Main entrypoint of the workflow.
# Please follow the best practices:
# https://snakemake.readthedocs.io/en/stable/snakefiles/best_practices.html,
# in particular regarding the standardized folder structure mentioned there.

import glob
import os


configfile: "config/config.yml"


input_dir = config["input_dir"]
output_dir = config["output_dir"]

# Collect sample names from test_data directory
SAMPLES = [os.path.basename(d) for d in glob.glob(f"{input_dir}/*") if os.path.isdir(d)]

# Define assembler names
ASSEMBLERS = ["spades", "megahit", "abyss", "sparseassembler", "minia", "masurca"]



# include common rule (where functions are defined)
include: "rules/common.smk"

# Conditionally include kmergenie rule only if using auto mode
if config["kmer_strategy"]["mode"] == "auto":
    include: "rules/kmergenie.smk"

# include spades rules
include: "rules/spades.smk"
# include megahit rule
include: "rules/megahit.smk"
# include abyss rule
include: "rules/abyss.smk"
# include decompress_reads rule
include: "rules/decompress_reads.smk"
# include sparseassembler rule
include: "rules/sparseassembler.smk"
# include minia rule
include: "rules/minia.smk"
# include masurca_config rule
include: "rules/masurca_config.smk"
# include masurca rule
include: "rules/masurca.smk"
# include busco rule
include: "rules/busco.smk"
# include quast rule
include: "rules/quast.smk"
# include fastK rule
include: "rules/fastK.smk"
# include merquryFK rule
include: "rules/merquryFK.smk"
# include bwa_mem2 rule
include: "rules/bwa_mem2_samtools.smk"
# include coverage visualization rule
include: "rules/coverage_viz.smk"
# include pilon rule
include: "rules/pilon.smk"
# include busco_2 rule (runs after pilon)
include: "rules/busco_2.smk"
# include merquryFK_2 rule
include: "rules/merquryFK_2.smk"
# include bwa_mem2_samtools_2 rule
include: "rules/bwa_mem2_samtools_2.smk"
#include coverage_viz_2 rule
include: "rules/coverage_viz_2.smk"
# include mapDamage2 rule
include: "rules/mapDamage2.smk"
# include mapDamage2_2 rule
include: "rules/mapDamage2_2.smk"

# input files for rule all are defined in the common.smk file
rule all:
    input:
        get_all_inputs()
