import glob
import os

configfile: "config.yaml"

input_dir = config["input_dir"]
output_dir = config["output_dir"]

# Collect sample names from test_data directory
SAMPLES = [os.path.basename(d) for d in glob.glob(f"{input_dir}/*") if os.path.isdir(d)]

rule all:
    input:
        expand(f"{output_dir}" + "/{sample}/scaffolds.fasta", sample=SAMPLES)

rule spades:
    input:
        forward_in= f"{input_dir}" + "/{sample}/{sample}_trimmed.R1.fq.gz",
        reverse_in= f"{input_dir}" + "/{sample}/{sample}_trimmed.R2.fq.gz",
    output:
        result_dir = directory(f"{output_dir}" + "/{sample}"),
        scaffolds = f"{output_dir}" + "/{sample}/scaffolds.fasta",
    threads: 2,  # access threads from config    
    shell:
        """
        spades.py -t {threads} -1 {input.forward_in} -2 {input.reverse_in} -o {output.result_dir} >> {log} 2>&1
        """

print("SAMPLES:", SAMPLES)