# to set up Snakemake for a Slurm cluster environment 
# for examples: https://github.com/jdblischak/smk-simple-slurm
# Snakemake profile for cluster-generic plugin documentation: https://snakemake.github.io/snakemake-plugin-catalog/plugins/executor/cluster-generic.html
# do not comment out lines in this file, if you do not want to use a specific option, just remove it


executor: cluster-generic
cluster-generic-submit-cmd:
  mkdir -p logs/{rule} &&
  sbatch
    --partition={resources.partition}
    --cpus-per-task={threads}
    --mem={resources.mem_mb}
    --job-name=smk-{rule}-{wildcards}
    --output=logs/{rule}/{rule}-{wildcards}-%j.out
    --parsable
default-resources:
  - partition=short
  - mem_mb=16000
restart-times: 3
max-jobs-per-second: 10
max-status-checks-per-second: 1
local-cores: 1
latency-wait: 60
jobs: 500
keep-going: True
rerun-incomplete: True
printshellcmds: True
scheduler: greedy
use-conda: True