# to set up Snakemake for a Slurm cluster environment 
# for examples: https://github.com/jdblischak/smk-simple-slurm
# Snakemake profile for Slurm plug in documentation: https://snakemake.github.io/snakemake-plugin-catalog/plugins/executor/slurm.html

executor: slurm
cluster-generic-submit-cmd:
  mkdir -p logs/{rule} &&
  sbatch
    --partition={resources.partition}
#    --qos={resources.qos}
    --cpus-per-task={threads}
    --mem={resources.mem_mb}
    --job-name=smk-{rule}-{wildcards}
    --output=logs/{rule}/{rule}-{wildcards}-%j.out
    --parsable
default-resources:
  - partition=short
#  - qos=<name-of-quality-of-service>
  - mem_mb=16000
  - runtime=24:00:00
restart-times: 3
max-jobs-per-second: 10
max-status-checks-per-second: 1
local-cores: 1
latency-wait: 60
jobs: 500
keep-going: True
rerun-incomplete: True
printshellcmds: True
scheduler: greedy
use-conda: True