# Set memory limit for rules
mem_mb: 16000
# Set number of threads for rules
threads: 8

# Set the path to the input directory (this directory must contain 
# one subdirectory for each sample, and the subdirectories must be named after the sample))
input_dir: "/home/lia/git_repos/FSP_assembly_benchmarking/test_data"

# Customise the results directory 
output_dir: "results"

# Customise spades parameters
spades:
  optional_params:
    "--careful": True
    "--only-assembler": True
#   "--disable-gzip-output": true
#   "--cov-cutoff": "auto"
#   "--min-contig-length": 500
