# Set memory limit for rules
mem_mb: 16000
# Set number of threads for rules
threads: 8

# Set the path to the input directory (this directory must contain
# one subdirectory for each sample, and the subdirectories must be named after the sample)
input_dir: "/home/lobinu/git_repos/FSP_assembly_benchmarking/test_data/clean_data/00_test/" # use absolute path and add trailing slash

# Customise the results directory
output_dir: "/home/lobinu/git_repos/FSP_assembly_benchmarking/results/" # use absolute path and add trailing slash

# Customise spades parameters
# please do not use the `-o` option here, it is set into the workflow
spades:
  optional_params:
    "--careful": True # tries to find and fix mismatches after the initial assembly is finished
    "--only-assembler": True # use this to skip the read error correction step (reads are already cleaned)
    "-k": "17,19,21,23" # k-mer sizes to use, adjust to your data

# Customise megahit parameters
megahit:
  optional_params:
    "--no-mercy": True
    "--min-count": 3 # suggested value for single genome assembly
    "--k-list": "31,51,71,91,99"

# Customise abyss parameters
# please do not use the `-j` and `-C` options here, they are set into the workflow
abyss:
  "k": 21
  "B": "16G" # note that this must be lower than "mem_mb", otherwise abyss fails. See docs at https://github.com/bcgsc/abyss?tab=readme-ov-file#bloom-filter-mode
  optional_params: # if you do not want to use any optional parameters, add `{}` here
    "kc": 2

# Customise sparseassembler parameters
sparseassembler:
  "k": 21
  "GS": 50000000 # genome size estimation in bp (used for memory pre-allocation), suggest a large value if possible.(e.g. ~ 3x genome size)
  "Scaffold": 1 # for scaffolding with paired-end reads, set to 1
  "ExpCov": 10 # expected coverage (for scaffolding)
  optional_params: # if you do not want to use any optional parameters, add `{}` here
    "g": 10
    "LD": 0
    "NodeCovTh": 1
    "EdgeCovTh": 0

# Customise minia parameters
minia:
  "k": 21
  optional_params: {} # if you do not want to use any optional parameters, add `{}` here
#    "-histo2D": 1 # enable 2D histogram output

# Customise masurca parameters
masurca:
  fragment_mean: 500 # mean insert size for your PE library (adjust to your data)
  fragment_stdev: 50 # stdev for your PE library (adjust to your data)
  kmer: auto # values between 25 and 127 are supported, auto will compute the optimal size based on the read data and GC content
  jf_size: 100000000 # this is mandatory jellyfish hash size -- a safe value is estimated_genome_size*20
  ca_parameters: cgwErrorRate=0.15 # set cgwErrorRate=0.25 for bacteria and 0.1<=cgwErrorRate<=0.15 for other organisms.
# Note that the following parameters are always set as follows:
# USE_GRID=0
# CLOSE_GAPS=1
# SOAP_ASSEMBLY=0
# MEGA_READS_ONE_PASS=0
# other parameters for long-reads, jump reads, mate-pairs, and slurm related options (customisable from masurca config) are ignored (for slurm, snakemake will take care of it).

# Customise busco parameters
busco:
  lineage_general: "/home/lobinu/git_repos/FSP_assembly_benchmarking/fungi_odb12" # chose a "general" dataset, in our case "fungi_odb10"
  lineage_specific: "/home/lobinu/git_repos/FSP_assembly_benchmarking/basidiomycota_odb12" # chose a more specific dataset, for example "basidiomycota_odb12", "ascomycota_odb12", etc.
  optional_params: # if you do not want to use any optional parameters, add `{}` here
    "--mode": "genome"
    "--metaeuk": True
    "--offline": True # use this if you do not want to download the lineage dataset from the web, but use a local copy instead

# Customise quast parameters
quast:
  optional_params: # if you do not want to use any optional parameters, add `{}` here
    "--circos": True # produces a Circos plot

# Customise fastK parameters
fastk:
  k: 17 # k-mer size, adjust to your data
  t: 1 # include kmer frequency >= t in the output

# Customise merquryfk parameters
merquryfk:
  optional_params: # if you do not want to use any optional parameters, add `{}` here
    "-z": True # outputs assembly plots in addition to spectra copy number
#    "-pdf": True # outputs results in PDF format (default is png)
