# Set memory limit for rules
mem_mb: 16000
# Set number of threads for rules
threads: 8

# Set the path to the input directory (this directory must contain 
# one subdirectory for each sample, and the subdirectories must be named after the sample))
input_dir: "/home/lobinu/git_repos/FSP_assembly_benchmarking/test_data/clean_data/00_test" # use absoolute path

# Customise the results directory 
output_dir: "/home/lobinu/git_repos/FSP_assembly_benchmarking/results_full" # use absolute path

# Customise spades parameters
spades:
  optional_params:
    "--careful": True
    "--only-assembler": True
#   "--disable-gzip-output": true
#   "--cov-cutoff": "auto"
#   "--min-contig-length": 500

# Customise megahit parameters
megahit:
  optional_params:
    "--no-mercy": True
    "--min-count": 3
    "--k-list": "31,51,71,91,99"

# Customise abyss parameters
abyss:
  "k": 21
  optional_params: {} # if you do not want to use any optional parameters, add `{}` here
#    "--some-flag": True
#    "--another-flag": False

# Customise sparseassembler parameters
sparseassembler:
  "k": 21
  "GS": 50000000 # genome size estimation in bp (used for memory pre-allocation), suggest a large value if possible.(e.g. ~ 3x genome size)
  "Scaffold": 1 # for scaffolding with paired-end reads, set to 1
  "ExpCov": 10 # expected coverage (for scaffolding)
  optional_params: {} # if you do not want to use any optional parameters, add `{}` here
#    "g": 10
#    "LD": 0
#    "NodeCovTh": 1
#    "EdgeCovTh": 0

# Customise minia parameters
minia:
  "k": 21
  optional_params: {} # if you do not want to use any optional parameters, add `{}` here

# Customise masurca parameters
masurca:
  insert_mean: 500         # mean insert size for your PE library (adjust to your data)
  insert_stdev: 50         # stdev for your PE library (adjust to your data)
  kmer: auto               # or set a specific value, e.g. 96
  jf_size: 100000000       # jellyfish hash size (adjust for your genome size)
  ca_parameters: cgwErrorRate=0.15  # adjust for your organism (0.25 for bacteria)


# Customise busco parameters
busco:
  lineage: "fungi_odb12" # or "fungi_odb10", "eukaryota_odb10", etc.
  optional_params:  # if you do not want to use any optional parameters, add `{}` here
    "--mode": "genome" 
    "--metaeuk": True

# Customise quast parameters
quast:
  optional_params: {} # if you do not want to use any optional parameters, add `{}` here