# Set memory limit for rules
mem_mb: 16000
# Set number of threads for rules
threads: 8

# Set the path to the input directory (this directory must contain 
# one subdirectory for each sample, and the subdirectories must be named after the sample))
input_path: "data/input/"

# Customise the results directory 
results_path: "data/output/"

# Customise spades parameters
spades:
  optional_params:
#    - "--careful": true
#    - "--only-assembler": true
#    - "--disable-gzip-output": true
#    - "--cov-cutoff": "auto"
#    - "--min-contig-length": 500